[workspace]

members = [
    "rosomaxa",
    "vrp-core",
    "vrp-cli",
    "vrp-api",
    "vrp-pragmatic",
    "vrp-scientific",

    "examples/json-pragmatic",
    "experiments/heuristic-research"
]

[profile.release]
incremental = true
lto = "fat"
codegen-units = 1
opt-level = 3
